table property_information
	lineageTag: aa759acf-d384-43c3-b14b-91f9cf2f42fd

	column 'Property ID'
		dataType: int64
		formatString: 0
		lineageTag: 617491f3-0084-4593-a862-e46430fa394c
		summarizeBy: none
		sourceColumn: Property ID

		annotation SummarizationSetBy = Automatic

	column 'Property Name'
		dataType: string
		lineageTag: cb6f21c1-b2e6-4903-9519-cc86d41a8749
		summarizeBy: none
		sourceColumn: Property Name

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: e2eba325-6d3a-46f9-adad-b8f1c1f4e2e1
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column 'Property Type'
		dataType: string
		lineageTag: c3cf93a0-c695-4c67-a0c0-8195ee02ccef
		summarizeBy: none
		sourceColumn: Property Type

		annotation SummarizationSetBy = Automatic

	column Amenities
		dataType: string
		lineageTag: 555df874-22f4-429f-a97e-4a5c69749f08
		summarizeBy: none
		sourceColumn: Amenities

		annotation SummarizationSetBy = Automatic

	column 'Historical Occupancy Rate (%)'
		dataType: int64
		formatString: 0
		lineageTag: 509a6b7e-f8dc-4994-af26-a3da6288c72b
		summarizeBy: none
		sourceColumn: Historical Occupancy Rate (%)

		annotation SummarizationSetBy = Automatic

	column 'Historical Occupancy rate Decimal' = property_information[Historical Occupancy Rate (%)]/100
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 8156a4ee-98c9-494f-bed0-ec9b4df65905
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition property_information = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Nel\Desktop\Data Analytics\Amdari\Tenant-Retention-Optimization-HomeVibe-Properties-\Dataset\property_information.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Property ID", Int64.Type}, {"Property Name", type text}, {"Location", type text}, {"Property Type", type text}, {"Amenities", type text}, {"Historical Occupancy Rate (%)", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

